### PR TITLE
Added optional feature to include Humble Choice games

### PR DESCRIPTION
**Pull request by ecenshu**
Added functionality to lookup Orders with type "subscriptioncontent" that has a page referenced from /membership/ url.

### CODE REVIEW

**Comment by jaredcat** [comment]
@ecenshu Could you create build for your fixes while we wait for @JustinHardage to merge them?

**Comment by ecenshu** [comment]
I actually don't know how to do that. Is that a GitHub action? I've only been building it from my local development environment.

**Comment by jaredcat** [comment]
@ecenshu yea just upload that dll or whatever to a release on your fork

**Comment by ecenshu** [comment]
I've added a GitHub action to do automated build and package the release
file on my branch now.

**Comment by jaredcat** [comment]
@ecenshu thank you! looks like it working pretty good! Not a big deal but my only suggestion would have been to name the files `YYYY-month` instead of the other way around, so they sort nicely.

**Comment by ecenshu** [comment]
I didn't change the version scheme since the original was using semver instead of calver

________________________________

**Comment by jaredcat** [comment]
@ecenshu not sure what you're talking about. i didn't mention version scheming. I'm talking about the new files created by the plugin

**Comment by ecenshu** [comment]
Sorry @jaredcat I thought you were referring to the build/release version numbers since that was the last thing I actioned and have that on my mind. What files are you referring to that has the date format `month-YYYY`? Are you referring to the tag title for the monthly bundles?

**Comment by jaredcat** [comment]
@ecenshu 
> What files are you referring to that has the date format `month-YYYY`? Are you referring to the tag title for the monthly bundles?

The cache files in the `membership` dir, againt just a nit pick.

I did find an issue where i have no more choices for a month but its still importing additional games into my library
image
-45bd-b999-f2e02d1592e8)

I double checked everywhere and i dont have this as a key from any other bundle.

**Comment by ecenshu** [comment]
I think I know why that is occurring, currently there is no logic to handle the scenario of limited number of selections in the month when that month has more games. My library doesn't have that use case, would you be able to send me the sanitized cache file for that month so I can attempt to replicate the workflow?

**Comment by jaredcat** [comment]
@ecenshu https://gist.github.com/jaredcat/6dd339f8545fc4593745312708eb172b

Also maybe enable issues on your repo? You might be the new maintainer of this (if you want)

**Comment by ecenshu** [comment]
Could you also send me the relevant redacted order as well? It is the file is in order folder and the filename corresponds to the `contentChoiceOptions.gamekey` of the 2020-february.json

The current issue I have is at the time the game is being processed to be added/removed from Playnite, it is an Order object and not the `IChoiceMonth `instance, if the data isn't available in the Order instance there may be some refactoring required to load and reference the `IChoiceMonth` during the Order processing.

**Comment by jaredcat** [comment]
@ecenshu `choices_remaining` makes it even easier: https://gist.github.com/jaredcat/6dd339f8545fc4593745312708eb172b#file-order-json-L773

**Comment by ecenshu** [comment]
Will be superceded by more comprehensive pull request

**Pull request closed without merging**
